language: ruby
rvm:
  - 2.2.2
bundler_args: -j4 --retry=3
script:
  - MAKEFLAGS+=-j8 bundle exec rake spec build binary --trace
  - MAKEFLAGS+=-j8 travis_wait gem install pkg/*.gem
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
cache: bundler